spring.application.name=hospitalfinderproj
spring.security.user.name=xxxx
spring.security.user.password=xxxx

spring.datasource.url=jdbc:mysql://localhost:3306/springproj
spring.datasource.username=xxxxx
spring.datasource.password=xxxxxxxx
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
